apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJvbWthcnA3NDEiLCJwYXNzd29yZCI6ImRja3JfcGF0X0ZraEtzSFB1cmlWZ2k1LXc5Z05xTGhRV2Q0byIsImVtYWlsIjoicG9ta2FyNzQxQGdtYWlsLmNvbSIsImF1dGgiOiJiMjFyWVhKd056UXhPbVJqYTNKZmNHRjBYMFpyYUV0elNGQjFjbWxXWjJrMUxYYzVaMDV4VEdoUlYyUTBidz09In19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: webapp
type: kubernetes.io/dockerconfigjson
